### ISSUE TITLE
About patch size

### ISSUE THREAD

**Issue by Rax111** [songzijiang/LGAN#1]
Hello, what is in the yml file
What are the patch sizes of ×2, ×3 and ×4 respectively?

**Comment by songzijiang** [comment]
Thank you for your attention to our work!
[configs](https://github.com/songzijiang/LGAN/tree/main/configs)/config.yml is the configuration of the network.
There are no rules about how to set patch sizes. You can set 'patch size' considering your GPUs` Memory. From experience, setting 'patch size' between 60 and 120 is a good choice. If you have enough Memory, you can set a larger path size for better perfencement.

The .yml file has been updated recently, I will upload a new config.yml later.
Hope this can help you.

**Comment by Rax111** [comment]
Thank you so much

**Comment by songzijiang** [comment]
I have checked the  config.yml. The latest version is the correct configuration. Using the default configuration in  config.yml will train an X4 model for 1000 epochs. I will update the meanings of the parameters, you can check the config.yml later.
